---
version: "3.9"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env-$RTE

  app:
    image: kea-bank:latest
    volumes:
      - media:/media/
      - static:/static/
      - .:/app/
    depends_on:
      - db
    env_file:
      - env-$RTE

  nginx:
    image: nginx:latest
    volumes:
      - media:/media/
      - static:/static/
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 8000:8000
    depends_on:
      - app

volumes:
  postgres_data:
  media:
  static:
