# Generated by Django 4.1.7 on 2023-03-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.rank'),
        ),
    ]
