# Generated by Django 4.1.7 on 2023-03-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_account_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='custome',
            new_name='customer',
        ),
    ]
