# Generated by Django 4.1.7 on 2023-04-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_rename_custome_loanrequest_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='is_approved',
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.customer')),
            ],
        ),
    ]
