# Generated by Django 4.1.7 on 2023-04-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_remove_loanrequest_is_approved_accountrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_approved',
        ),
        migrations.CreateModel(
            name='ApprovedLoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.account')),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.loanrequest')),
            ],
        ),
    ]
