# Generated by Django 4.1.7 on 2023-04-22 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_app', '0011_loanrequest_status_delete_approvedloanrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('not reviewed', 'not reviewed'), ('approved', 'approved'), ('declined', 'declined')], db_index=True, default='not reviewed', max_length=25),
        ),
        migrations.CreateModel(
            name='ApprovedLoanRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.account')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.loanrequest')),
            ],
        ),
    ]
