# Generated by Django 4.1.7 on 2023-04-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0014_approvedaccountrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='status',
            field=models.CharField(choices=[('not reviewed', 'not reviewed'), ('approved', 'approved'), ('declined', 'declined')], db_index=True, default='not reviewed', max_length=25),
        ),
    ]
