# Generated by Django 4.1.7 on 2023-04-30 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0016_alter_approvedaccountrequests_account_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedaccountrequests',
            name='account_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.accountrequest'),
        ),
        migrations.AlterField(
            model_name='approvedloanrequests',
            name='loan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.loanrequest'),
        ),
    ]
