# Generated by Django 4.1.7 on 2023-05-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0017_alter_approvedaccountrequests_account_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_loan',
            field=models.BooleanField(default=False),
        ),
    ]
