# Generated by Django 4.1.7 on 2023-05-15 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0017_alter_approvedaccountrequests_account_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
    ]
