# Generated by Django 4.1.7 on 2023-05-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0018_account_is_loan'),
        ('bank_app', '0018_remove_ledger_timestamp_transaction_datetime'),
    ]

    operations = [
    ]
