# Generated by Django 4.1.7 on 2023-05-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0019_merge_20230518_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='message',
            field=models.TextField(max_length=40),
        ),
    ]
