# Generated by Django 4.1.7 on 2023-05-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0020_alter_ledger_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['transaction']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-datetime']},
        ),
    ]
